name: Weekly Macro Calendar Update

on:
  schedule:
    - cron: '0 9 * * 1'  # Every Monday at 9:00 UTC
  workflow_dispatch:      # Manual trigger button

jobs:
  update-calendar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run calendar builder script
        env:
          TE_CLIENT: ${{ secrets.TE_CLIENT }}
          TE_SECRET: ${{ secrets.TE_SECRET }}
        run: python calendar_builder_full.py

      - name: Commit and push updated Excel
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add macro_calendar.xlsx
          git commit -m "📈 Weekly macro calendar update"
          git push
